[project]
name = "vocab-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.11"
dependencies = [
    "langchain>=0.3.26",
    "langchain-community>=0.3.26",
    "streamlit>=1.44.1",
    "youtube-transcript-api>=1.1.0",
]
